config/routes.rb
Rails.application.routes.draw do

  get 'gephis/index', :as => 'gephi'
  get 'application/tableau'

  resources :datosbasicos
  resources :places
  resources :cities
  devise_for :users
  resources :users_admin, :controller => 'users'

  authenticate :user do
    get 'application/admin'
    get 'artworks/admin'

    resources :iconographic_attributes
    resources :artwork_symbols
    resources :phylactery_billboards
    resources :engravings
    resources :descriptions
    resources :body_gestures
    resources :schools
    resources :story_types
    resources :passages
    resources :characters
    resources :donors
    resources :scenes
    resources :sources
    resources :types
    resources :countries
    resources :authors

    put 'artworks/send_image'

    resources :categories do
      get 'get_children_for_select', :on => :member
    end

    resources :artworks, except: [:index, :show]

  end

  resources :artworks do
    member do
      get 'line'
    end
    resources :categories
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/models/donor.rb
class Donor < ActiveRecord::Base

  validates_presence_of :name, :message => "Tiene que ingresar un nombre para el donador"
  validates :name, uniqueness: { case_sensitive: false , message: "Ya existe un donador con el mismo nombre" }


  has_many :artworks
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all.paginate(page: params[:page], per_page: 50).order('name ASC')
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:name)
    end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% @donor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing donor</h1>

<%= render 'form' %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<h1>Listing donors</h1>
<%= link_to 'New Donor', new_donor_path %>

<div id="donadores">
  <input class="search" placeholder="Buscar" />

  <button class="sort" data-sort="nombre">
    Ordenar por Nombre
  </button>

    <table  class="table table-bordered table-condensed table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="list">
        <% @donors.each do |donor| %>
          <tr>
            <td class="nombre"><%= donor.name %></td>
            <td><%= link_to 'Show', donor %></td>
            <td><%= link_to 'Edit', edit_donor_path(donor) %></td>
            <td><%= link_to 'Destroy', donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <br>
  <%= will_paginate @donors,  renderer: BootstrapPagination::Rails %>
</div>
<script>
    var options = {
        valueNames: ['nombre']
    };

    var userList = new List('donadores', options);
</script>

app/views/donors/new.html.erb
<h1>New donor</h1>

<%= render 'form' %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @donor.name %>
</p>

<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>