config/routes.rb
Rails.application.routes.draw do

  get 'gephis/index', :as => 'gephi'
  get 'application/tableau'

  resources :datosbasicos
  resources :places
  resources :cities
  devise_for :users
  resources :users_admin, :controller => 'users'

  authenticate :user do
    get 'application/admin'
    get 'artworks/admin'

    resources :iconographic_attributes
    resources :artwork_symbols
    resources :phylactery_billboards
    resources :engravings
    resources :descriptions
    resources :body_gestures
    resources :schools
    resources :story_types
    resources :passages
    resources :characters
    resources :donors
    resources :scenes
    resources :sources
    resources :types
    resources :countries
    resources :authors

    put 'artworks/send_image'

    resources :categories do
      get 'get_children_for_select', :on => :member
    end

    resources :artworks, except: [:index, :show]

  end

  resources :artworks do
    member do
      get 'line'
    end
    resources :categories
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/models/scene.rb
class Scene < ActiveRecord::Base

  validates_presence_of :name, :message => "Tiene que ingresar un nombre para la escena"
  validates :name, uniqueness: { case_sensitive: false , message: "Ya existe una escena con el mismo nombre" }


  has_many :artworks
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /scenes
  # GET /scenes.json
  def index
    @scenes = Scene.all.paginate(page: params[:page], per_page: 50).order('name ASC')
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show
  end

  # GET /scenes/new
  def new
    @scene = Scene.new
  end

  # GET /scenes/1/edit
  def edit
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @scene = Scene.new(scene_params)

    respond_to do |format|
      if @scene.save
        format.html { redirect_to @scene, notice: 'Scene was successfully created.' }
        format.json { render :show, status: :created, location: @scene }
      else
        format.html { render :new }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { render :show, status: :ok, location: @scene }
      else
        format.html { render :edit }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenes_url, notice: 'Scene was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = Scene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scene_params
      params.require(:scene).permit(:name)
    end
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_form.html.erb
<%= form_for(@scene) do |f| %>
  <% if @scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% @scene.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name, class:"form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing scene</h1>

<%= render 'form' %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

app/views/scenes/index.html.erb
<h1>Listing scenes</h1>
<%= link_to 'New Scene', new_scene_path %>

<div id="scene">
  <input class="search" placeholder="Buscar" />

  <button class="sort" data-sort="nombre">
    Ordenar por Nombre
  </button>

  <table  class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="list">
    <% @scenes.each do |scene| %>
      <tr>
        <td class="nombre"><%= scene.name %></td>
        <td><%= link_to 'Show', scene %></td>
        <td><%= link_to 'Edit', edit_scene_path(scene) %></td>
        <td><%= link_to 'Destroy', scene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <br>
  <%= will_paginate @scenes,  renderer: BootstrapPagination::Rails %>
</div>

<script>
    var options = {
        valueNames: ['nombre']
    };

    var userList = new List('scene', options);
</script>

app/views/scenes/new.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scene.name %>
</p>

<%= link_to 'Edit', edit_scene_path(@scene) %> |
<%= link_to 'Back', scenes_path %>