config/routes.rb
Rails.application.routes.draw do

  get 'gephis/index', :as => 'gephi'
  get 'application/tableau'

  resources :datosbasicos
  resources :places
  resources :cities
  devise_for :users
  resources :users_admin, :controller => 'users'

  authenticate :user do
    get 'application/admin'
    get 'artworks/admin'

    resources :iconographic_attributes
    resources :artwork_symbols
    resources :phylactery_billboards
    resources :engravings
    resources :descriptions
    resources :body_gestures
    resources :schools
    resources :story_types
    resources :passages
    resources :characters
    resources :donors
    resources :scenes
    resources :sources
    resources :types
    resources :countries
    resources :authors

    put 'artworks/send_image'

    resources :categories do
      get 'get_children_for_select', :on => :member
    end

    resources :artworks, except: [:index, :show]

  end

  resources :artworks do
    member do
      get 'line'
    end
    resources :categories
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/models/engraving.rb
class Engraving < ActiveRecord::Base
  has_and_belongs_to_many :artworks
end

app/controllers/engravings_controller.rb
class EngravingsController < ApplicationController
  before_action :set_engraving, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /engravings
  # GET /engravings.json
  def index
    @engravings = Engraving.all.paginate(page: params[:page], per_page: 50).order('name ASC')
  end

  # GET /engravings/1
  # GET /engravings/1.json
  def show
  end

  # GET /engravings/new
  def new
    @engraving = Engraving.new
  end

  # GET /engravings/1/edit
  def edit
  end

  # POST /engravings
  # POST /engravings.json
  def create
    @engraving = Engraving.new(engraving_params)

    respond_to do |format|
      if @engraving.save
        format.html { redirect_to @engraving, notice: 'Engraving was successfully created.' }
        format.json { render :show, status: :created, location: @engraving }
      else
        format.html { render :new }
        format.json { render json: @engraving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engravings/1
  # PATCH/PUT /engravings/1.json
  def update
    respond_to do |format|
      if @engraving.update(engraving_params)
        format.html { redirect_to @engraving, notice: 'Engraving was successfully updated.' }
        format.json { render :show, status: :ok, location: @engraving }
      else
        format.html { render :edit }
        format.json { render json: @engraving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engravings/1
  # DELETE /engravings/1.json
  def destroy
    @engraving.destroy
    respond_to do |format|
      format.html { redirect_to engravings_url, notice: 'Engraving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engraving
      @engraving = Engraving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engraving_params
      params.require(:engraving).permit(:name)
    end
end

app/helpers/engravings_helper.rb
module EngravingsHelper
end

app/views/engravings/_form.html.erb
<%= form_for(@engraving) do |f| %>
  <% if @engraving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engraving.errors.count, "error") %> prohibited this engraving from being saved:</h2>

      <ul>
      <% @engraving.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name, class:"form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/engravings/edit.html.erb
<h1>Editing engraving</h1>

<%= render 'form' %>

<%= link_to 'Show', @engraving %> |
<%= link_to 'Back', engravings_path %>

app/views/engravings/index.html.erb
<h1>Listing engravings</h1>
<%= link_to 'New Engraving', new_engraving_path %>

<div id="engraving">
  <input class="search" placeholder="Buscar" />

  <button class="sort" data-sort="nombre">
    Ordenar por Nombre
  </button>

  <table  class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="list">
    <% @engravings.each do |engraving| %>
      <tr>
        <td class="nombre"><%= engraving.name %></td>
        <td><%= link_to 'Show', engraving %></td>
        <td><%= link_to 'Edit', edit_engraving_path(engraving) %></td>
        <td><%= link_to 'Destroy', engraving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <br>
  <%= will_paginate @engravings,  renderer: BootstrapPagination::Rails %>
</div>

<script>
  var options = {
      valueNames: ['nombre']
  };

  var userList = new List('engraving', options);
</script>

app/views/engravings/new.html.erb
<h1>New engraving</h1>

<%= render 'form' %>

<%= link_to 'Back', engravings_path %>

app/views/engravings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @engraving.name %>
</p>

<%= link_to 'Edit', edit_engraving_path(@engraving) %> |
<%= link_to 'Back', engravings_path %>