config/routes.rb
Rails.application.routes.draw do

  get 'gephis/index', :as => 'gephi'
  get 'application/tableau'

  resources :datosbasicos
  resources :places
  resources :cities
  devise_for :users
  resources :users_admin, :controller => 'users'

  authenticate :user do
    get 'application/admin'
    get 'artworks/admin'

    resources :iconographic_attributes
    resources :artwork_symbols
    resources :phylactery_billboards
    resources :engravings
    resources :descriptions
    resources :body_gestures
    resources :schools
    resources :story_types
    resources :passages
    resources :characters
    resources :donors
    resources :scenes
    resources :sources
    resources :types
    resources :countries
    resources :authors

    put 'artworks/send_image'

    resources :categories do
      get 'get_children_for_select', :on => :member
    end

    resources :artworks, except: [:index, :show]

  end

  resources :artworks do
    member do
      get 'line'
    end
    resources :categories
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/models/passage.rb
class Passage < ActiveRecord::Base
  validates_presence_of :name, :message => "Tiene que ingresar un nombre para el pasaje."
  validates :name, uniqueness: { case_sensitive: false , message: "Ya existe un pasaje con el mismo nombre" }

  has_many :artworks


  def get_history_type
    history_type ? history_type : "N/A"
  end


end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  before_action :set_passage, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /passages
  # GET /passages.json
  def index
    @passages = Passage.all.paginate(page: params[:page], per_page: 50).order('name ASC')
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
  end

  # GET /passages/new
  def new
    @passage = Passage.new
  end

  # GET /passages/1/edit
  def edit
  end

  # POST /passages
  # POST /passages.json
  def create
    @passage = Passage.new(passage_params)

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render :show, status: :created, location: @passage }
      else
        format.html { render :new }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passages/1
  # PATCH/PUT /passages/1.json
  def update
    respond_to do |format|
      if @passage.update(passage_params)
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { render :show, status: :ok, location: @passage }
      else
        format.html { render :edit }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passages/1
  # DELETE /passages/1.json
  def destroy
    @passage.destroy
    respond_to do |format|
      format.html { redirect_to passages_url, notice: 'Passage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passage
      @passage = Passage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passage_params
      params.require(:passage).permit(:name,:text,:history_type,:source)
    end
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/passages/_form.html.erb
<%= form_for(@passage) do |f| %>
  <% if @passage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passage.errors.count, "error") %> prohibited this passage from being saved:</h2>

      <ul>
      <% @passage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text, cols: "100", rows: "10" %>
  </div>
  <div class="field">
    <%= f.label :history_type %><br>
    <%= f.text_area :history_type %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_area :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passages/edit.html.erb
<h1>Editing passage</h1>

<%= render 'form' %>

<%= link_to 'Show', @passage %> |
<%= link_to 'Back', passages_path %>

app/views/passages/index.html.erb
<h1>Listing passages</h1>
<%= link_to 'New Passage', new_passage_path %>

<div id="passage">
  <input class="search" placeholder="Buscar" />

  <button class="sort" data-sort="nombre">
    Ordenar por Nombre
  </button>

  <table  class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Pasaje</th>
      <th>Tipo de historia</th>
      <th>Fuente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

    <tbody class="list">
        <% @passages.each do |passage| %>
          <tr>
            <td class="nombre"><%= passage.name %></td>
            <td class="nombre"><%= passage.text %></td>
            <td class="nombre"><%= passage.history_type %></td>
            <td class="nombre"><%= passage.source %></td>
            <td><%= link_to 'Show', passage %></td>
            <td><%= link_to 'Edit', edit_passage_path(passage) %></td>
            <td><%= link_to 'Destroy', passage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    </tbody>
</table>
  <br>
  <%= will_paginate @passages,  renderer: BootstrapPagination::Rails %>
</div>

<script>
    var options = {
        valueNames: ['nombre']
    };

    var userList = new List('passage', options);
</script>

app/views/passages/new.html.erb
<h1>New passage</h1>

<%= render 'form' %>

<%= link_to 'Back', passages_path %>

app/views/passages/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<p>
  <strong>Nombre:</strong>
  <%= @passage.name %>
</p>
<p>
  <strong>Pasaje:</strong>
  <%= @passage.text %>
</p>
<p>
  <strong>Tipo de historia:</strong>
  <%= @passage.history_type %>
</p>
<p>
  <strong>Fuente:</strong>
  <%= @passage.source %>
</p>

<%= link_to 'Edit', edit_passage_path(@passage) %> |
<%= link_to 'Back', passages_path %>